### PR TITLE
elasticsearch: records and facet configuration in jsonalchemy

### PR DESCRIPTION
**Pull request by jma**
Signed-off-by: Johnny Mariéthoz Johnny.Mariethoz@rero.ch

### CODE REVIEW

**Comment by jirikuncar** [comment]
@nharraud can we try to port it to `SEARCH_RECORD_MAPPING`? More IRL

**Comment by jma** [comment]
Hello, just a naive question: is it possible to move it in the json schema definition?

Sorry for disturbing.

**Comment by jirikuncar** [comment]
@jma unfortunately it's not planed for current version.

**Comment by jma** [comment]
Ok but is SEARCH_RECORD_MAPPING will be moved into the config?

**Comment by jirikuncar** [comment]
@jma yes, we should think about having *json* config files per record type ... this one could be an example for MARC21 standard based on DoJSON.

**Comment by tiborsimko** [comment]
@jirikuncar @nharraud We should probably close this PR and make a new issue for `SEARCH_RECORD_MAPPING`, considering the code base changed a lot...

**Comment by jirikuncar** [comment]
Solved by sending mappings directly to ES in Invenio 3.

**Pull request closed without merging**
